#if !defined(__ERROR_CODES_H)
#define __ERROR_CODES_H

#define ERR_OUT_OF_MEMORY 1
#define ERR_MISSING_ARGUMENTS 2
#define ERR_INVALID_PROGRAM_FILE 3
#define ERR_INVALID_REGISTER_ACCESS 4
#define ERR_MEMORY_ACCESS_INVALID 5
#define ERR_PROGRAM_EXECUTION_ENDED_UNEXPECTEDLY 6
#define ERR_INVALID_OPCODE 6
#define ERR_DIVISION_BY_ZERO 7

#endif /* __ERROR_CODES_H */
